language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t vangalasantosh/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true vangalasantosh/docker-react npm run test